// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AckMessageCallback(arg1, arg2) {
  return window['go']['impl']['node']['AckMessageCallback'](arg1, arg2);
}

export function AckTicker(arg1, arg2) {
  return window['go']['impl']['node']['AckTicker'](arg1, arg2);
}

export function AddBlockAndName(arg1) {
  return window['go']['impl']['node']['AddBlockAndName'](arg1);
}

export function AddPeer(arg1) {
  return window['go']['impl']['node']['AddPeer'](arg1);
}

export function AddRequest(arg1) {
  return window['go']['impl']['node']['AddRequest'](arg1);
}

export function AntiEntropyTicker() {
  return window['go']['impl']['node']['AntiEntropyTicker']();
}

export function ApplyOperation(arg1) {
  return window['go']['impl']['node']['ApplyOperation'](arg1);
}

export function Broadcast(arg1) {
  return window['go']['impl']['node']['Broadcast'](arg1);
}

export function CRDTOperationsMessageCallback(arg1, arg2) {
  return window['go']['impl']['node']['CRDTOperationsMessageCallback'](arg1, arg2);
}

export function ChatMessageCallback(arg1, arg2) {
  return window['go']['impl']['node']['ChatMessageCallback'](arg1, arg2);
}

export function CreateBudgetMap(arg1, arg2) {
  return window['go']['impl']['node']['CreateBudgetMap'](arg1, arg2);
}

export function DataReplyMessageCallback(arg1, arg2) {
  return window['go']['impl']['node']['DataReplyMessageCallback'](arg1, arg2);
}

export function DataRequestMessageCallback(arg1, arg2) {
  return window['go']['impl']['node']['DataRequestMessageCallback'](arg1, arg2);
}

export function DeleteAck(arg1) {
  return window['go']['impl']['node']['DeleteAck'](arg1);
}

export function DeleteDataReplyChan(arg1) {
  return window['go']['impl']['node']['DeleteDataReplyChan'](arg1);
}

export function DeleteSearchReplyChan(arg1) {
  return window['go']['impl']['node']['DeleteSearchReplyChan'](arg1);
}

export function Download(arg1) {
  return window['go']['impl']['node']['Download'](arg1);
}

export function DownloadElement(arg1) {
  return window['go']['impl']['node']['DownloadElement'](arg1);
}

export function EmptyMessageCallback(arg1, arg2) {
  return window['go']['impl']['node']['EmptyMessageCallback'](arg1, arg2);
}

export function ExpandRing(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['impl']['node']['ExpandRing'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ForwardSearchRequest(arg1, arg2, arg3, arg4) {
  return window['go']['impl']['node']['ForwardSearchRequest'](arg1, arg2, arg3, arg4);
}

export function GetAck(arg1) {
  return window['go']['impl']['node']['GetAck'](arg1);
}

export function GetBlockOps(arg1, arg2) {
  return window['go']['impl']['node']['GetBlockOps'](arg1, arg2);
}

export function GetCRDTState(arg1) {
  return window['go']['impl']['node']['GetCRDTState'](arg1);
}

export function GetCatalog() {
  return window['go']['impl']['node']['GetCatalog']();
}

export function GetDocumentOps(arg1) {
  return window['go']['impl']['node']['GetDocumentOps'](arg1);
}

export function GetEditor() {
  return window['go']['impl']['node']['GetEditor']();
}

export function GetFileInfo(arg1, arg2) {
  return window['go']['impl']['node']['GetFileInfo'](arg1, arg2);
}

export function GetNeighbors(arg1) {
  return window['go']['impl']['node']['GetNeighbors'](arg1);
}

export function GetRandNeighsFromBudget(arg1, arg2) {
  return window['go']['impl']['node']['GetRandNeighsFromBudget'](arg1, arg2);
}

export function GetRandomNeighborFromRoutingTable(arg1) {
  return window['go']['impl']['node']['GetRandomNeighborFromRoutingTable'](arg1);
}

export function GetRandomPeerFromCatalog(arg1) {
  return window['go']['impl']['node']['GetRandomPeerFromCatalog'](arg1);
}

export function GetRoutingTable() {
  return window['go']['impl']['node']['GetRoutingTable']();
}

export function HeartbeatTicker() {
  return window['go']['impl']['node']['HeartbeatTicker']();
}

export function HexEncode(arg1) {
  return window['go']['impl']['node']['HexEncode'](arg1);
}

export function Listen() {
  return window['go']['impl']['node']['Listen']();
}

export function PaxosAcceptMessageCallback(arg1, arg2) {
  return window['go']['impl']['node']['PaxosAcceptMessageCallback'](arg1, arg2);
}

export function PaxosLoop(arg1, arg2) {
  return window['go']['impl']['node']['PaxosLoop'](arg1, arg2);
}

export function PaxosPrepareMessageCallback(arg1, arg2) {
  return window['go']['impl']['node']['PaxosPrepareMessageCallback'](arg1, arg2);
}

export function PaxosPromiseMessageCallback(arg1, arg2) {
  return window['go']['impl']['node']['PaxosPromiseMessageCallback'](arg1, arg2);
}

export function PaxosProposeMessageCallback(arg1, arg2) {
  return window['go']['impl']['node']['PaxosProposeMessageCallback'](arg1, arg2);
}

export function PrivateMessageCallback(arg1, arg2) {
  return window['go']['impl']['node']['PrivateMessageCallback'](arg1, arg2);
}

export function ProcessMsg(arg1) {
  return window['go']['impl']['node']['ProcessMsg'](arg1);
}

export function ProcessRumor(arg1, arg2) {
  return window['go']['impl']['node']['ProcessRumor'](arg1, arg2);
}

export function RelayMsg(arg1) {
  return window['go']['impl']['node']['RelayMsg'](arg1);
}

export function RemoteDownload(arg1) {
  return window['go']['impl']['node']['RemoteDownload'](arg1);
}

export function RemovePeerFromCatalog(arg1, arg2) {
  return window['go']['impl']['node']['RemovePeerFromCatalog'](arg1, arg2);
}

export function Resolve(arg1) {
  return window['go']['impl']['node']['Resolve'](arg1);
}

export function RumorsMessageCallback(arg1, arg2) {
  return window['go']['impl']['node']['RumorsMessageCallback'](arg1, arg2);
}

export function SaveTransactions(arg1) {
  return window['go']['impl']['node']['SaveTransactions'](arg1);
}

export function SearchAll(arg1, arg2, arg3) {
  return window['go']['impl']['node']['SearchAll'](arg1, arg2, arg3);
}

export function SearchFirst(arg1, arg2) {
  return window['go']['impl']['node']['SearchFirst'](arg1, arg2);
}

export function SearchFirstLocal(arg1) {
  return window['go']['impl']['node']['SearchFirstLocal'](arg1);
}

export function SearchMatch(arg1) {
  return window['go']['impl']['node']['SearchMatch'](arg1);
}

export function SearchReplyMessageCallback(arg1, arg2) {
  return window['go']['impl']['node']['SearchReplyMessageCallback'](arg1, arg2);
}

export function SearchRequestMessageCallback(arg1, arg2) {
  return window['go']['impl']['node']['SearchRequestMessageCallback'](arg1, arg2);
}

export function SendAckMessage(arg1) {
  return window['go']['impl']['node']['SendAckMessage'](arg1);
}

export function SendDataRequestMessage(arg1, arg2, arg3) {
  return window['go']['impl']['node']['SendDataRequestMessage'](arg1, arg2, arg3);
}

export function SendHeartbeat() {
  return window['go']['impl']['node']['SendHeartbeat']();
}

export function SendMsg(arg1, arg2) {
  return window['go']['impl']['node']['SendMsg'](arg1, arg2);
}

export function SendRumorsMessage(arg1, arg2) {
  return window['go']['impl']['node']['SendRumorsMessage'](arg1, arg2);
}

export function SendRumorsMessageRand(arg1, arg2) {
  return window['go']['impl']['node']['SendRumorsMessageRand'](arg1, arg2);
}

export function SendSearchRequestMessage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['impl']['node']['SendSearchRequestMessage'](arg1, arg2, arg3, arg4, arg5);
}

export function SendStatusMessage(arg1, arg2) {
  return window['go']['impl']['node']['SendStatusMessage'](arg1, arg2);
}

export function SendWithProbability(arg1, arg2) {
  return window['go']['impl']['node']['SendWithProbability'](arg1, arg2);
}

export function SetAck(arg1, arg2) {
  return window['go']['impl']['node']['SetAck'](arg1, arg2);
}

export function SetDataReplyChan(arg1, arg2) {
  return window['go']['impl']['node']['SetDataReplyChan'](arg1, arg2);
}

export function SetRoutingEntry(arg1, arg2) {
  return window['go']['impl']['node']['SetRoutingEntry'](arg1, arg2);
}

export function SetSearchReplyChan(arg1, arg2) {
  return window['go']['impl']['node']['SetSearchReplyChan'](arg1, arg2);
}

export function SplitMetafile(arg1) {
  return window['go']['impl']['node']['SplitMetafile'](arg1);
}

export function Start() {
  return window['go']['impl']['node']['Start']();
}

export function StatusMessageCallback(arg1, arg2) {
  return window['go']['impl']['node']['StatusMessageCallback'](arg1, arg2);
}

export function Stop() {
  return window['go']['impl']['node']['Stop']();
}

export function TLCMessageCallback(arg1, arg2) {
  return window['go']['impl']['node']['TLCMessageCallback'](arg1, arg2);
}

export function TLCStepReset() {
  return window['go']['impl']['node']['TLCStepReset']();
}

export function Tag(arg1, arg2) {
  return window['go']['impl']['node']['Tag'](arg1, arg2);
}

export function TryBroadcast(arg1) {
  return window['go']['impl']['node']['TryBroadcast'](arg1);
}

export function Unicast(arg1, arg2) {
  return window['go']['impl']['node']['Unicast'](arg1, arg2);
}

export function UpdateCatalog(arg1, arg2) {
  return window['go']['impl']['node']['UpdateCatalog'](arg1, arg2);
}

export function UpdateEditor(arg1) {
  return window['go']['impl']['node']['UpdateEditor'](arg1);
}

export function Upload(arg1) {
  return window['go']['impl']['node']['Upload'](arg1);
}
