// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function HTML():Promise<string>;

export function Name():Promise<string>;

export function NewEmpty():Promise<types.Message>;

export function String():Promise<string>;
