// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function HTML() {
  return window['go']['types']['CRDTOperationsMessage']['HTML']();
}

export function Name() {
  return window['go']['types']['CRDTOperationsMessage']['Name']();
}

export function NewEmpty() {
  return window['go']['types']['CRDTOperationsMessage']['NewEmpty']();
}

export function String() {
  return window['go']['types']['CRDTOperationsMessage']['String']();
}
