import { PartialBlock } from "@blocknote/core";

const mockDocument: PartialBlock[] = [
  {
    id: "1@temp",
    type: "paragraph",
    content: [
      {
        type: "text",
        text: "Welcome to the BlockNote Editor",
        // @ts-ignore
        charIds: [
          "2@temp",
          "3@temp",
          "4@temp",
          "5@temp",
          "6@temp",
          "7@temp",
          "8@temp",
          "9@temp",
          "10@temp",
          "11@temp",
          "12@temp",
          "13@temp",
          "14@temp",
          "15@temp",
          "16@temp",
          "17@temp",
          "18@temp",
          "19@temp",
          "20@temp",
          "21@temp",
          "22@temp",
          "23@temp",
          "24@temp",
          "25@temp",
          "26@temp",
          "27@temp",
          "28@temp",
          "29@temp",
          "30@temp",
          "31@temp",
          "32@temp",
        ],
        styles: {},
      },
    ],
  },
  {
    id: "2@temp",
    type: "paragraph",
    content: [
      {
        type: "text",
        text: "<- Notice the new button in the side menu",
        // @ts-ignore
        charIds: [
          "1@temp",
          "2@temp",
          "3@temp",
          "4@temp",
          "5@temp",
          "6@temp",
          "7@temp",
          "8@temp",
          "9@temp",
          "10@temp",
          "11@temp",
          "12@temp",
          "13@temp",
          "14@temp",
          "15@temp",
          "16@temp",
          "17@temp",
          "18@temp",
          "19@temp",
          "20@temp",
          "21@temp",
          "22@temp",
          "23@temp",
          "24@temp",
          "25@temp",
          "26@temp",
          "27@temp",
          "28@temp",
          "29@temp",
          "30@temp",
          "31@temp",
          "32@temp",
          "33@temp",
          "34@temp",
          "35@temp",
          "36@temp",
          "37@temp",
          "38@temp",
          "39@temp",
          "40@temp",
          "41@temp",
        ],
        styles: {},
      },
    ],
  },
  {
    id: "3@temp",
    type: "paragraph",
    content: [
      {
        type: "text",
        text: "Click it to remove the hovered block",
        // @ts-ignore
        charIds: [
          "1@temp",
          "2@temp",
          "3@temp",
          "4@temp",
          "5@temp",
          "6@temp",
          "7@temp",
          "8@temp",
          "9@temp",
          "10@temp",
          "11@temp",
          "12@temp",
          "13@temp",
          "14@temp",
          "15@temp",
          "16@temp",
          "17@temp",
          "18@temp",
          "19@temp",
          "20@temp",
          "21@temp",
          "22@temp",
          "23@temp",
          "24@temp",
          "25@temp",
          "26@temp",
          "27@temp",
          "28@temp",
          "29@temp",
          "30@temp",
          "31@temp",
          "32@temp",
          "33@temp",
          "34@temp",
          "35@temp",
          "36@temp",
        ],
        styles: {},
      },
    ],
  },
  {
    id: "4@temp",
    type: "paragraph",
    content: [
      {
        type: "text",
        text: "",
        // @ts-ignore
        charIds: [],
        styles: {},
      },
    ],
  },
];

export default mockDocument;
