// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

/**
 * Regexp is the representation of a compiled regular expression.
 * A Regexp is safe for concurrent use by multiple goroutines,
 * except for configuration methods, such as [Regexp.Longest].
 */
export type Regexp = string;
