name: BalduchColab_tests

on:
  push

jobs:
  tests:
    runs-on:
      group: runners_v1
    env:
      LLVL: trace
    steps:
      - name: Use Go = 1.23
        uses: actions/setup-go@v3
        with:
          go-version: '=1.23'
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      # Install gotestfmt on the VM running the action.
      - name: Set up gotestfmt
        uses: gotesttools/gotestfmt-action@v2
        with:
          # Pass GITHUB_TOKEN to avoid rate limiting.
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create temp directory
        run: |
          mkdir -p ./${{ github.run_attempt }}

      # Run tests with nice formatting
      - name: Run unit tests
        run: |
          set -euo pipefail
          go test -json -timeout 5m -v -race -run Test_Editor ./backend/peer/tests/unit 2>&1 | tee ./${{ github.run_attempt }}/gotest-unit.log | gotestfmt
          go test -json -timeout 5m -v -race -run Test_Document ./backend/peer/tests/unit 2>&1 | tee ./${{ github.run_attempt }}/gotest-unit.log | gotestfmt
          go test -json -timeout 5m -v -race -run Test_SaveTransactions ./backend/peer/tests/unit 2>&1 | tee ./${{ github.run_attempt }}/gotest-unit.log | gotestfmt

    

      # Upload formatted logs
      - name: Upload unit test log
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-balduchColab-log
          path: ./${{ github.run_attempt }}/gotest-unit.log
          if-no-files-found: error


